import type { OxfmtConfig, OxfmtOverrideConfig } from '@finografic/oxc-config/oxfmt';
import {
  AGENT_DOC_MARKDOWN_PATHS,
  agentMarkdown,
  base,
  css,
  ignorePatterns,
  json,
  markdown,
  sorting,
} from '@finografic/oxc-config/oxfmt';
import { defineConfig } from 'oxfmt';

export default defineConfig({
  ignorePatterns: [
    ...ignorePatterns,
    // Generated by icons-server (column-aligned registry); oxfmt would collapse padding.
    'packages/icons/icons.generated.ts',
    // Generated by packages/icons/scripts/sync-generated-index.mjs; oxfmt jsdoc
    // capitalizeDescriptions rewrites `index.ts` → `Index.ts` in the file header.
    'packages/icons/index.ts',
  ],
  ...base,
  ...sorting,
  overrides: [
    { files: ['*.json', '*.jsonc'], excludeFiles: [], options: { ...json } },
    {
      files: ['*.md', '*.mdx'],
      excludeFiles: [...AGENT_DOC_MARKDOWN_PATHS],
      options: { ...markdown },
    },
    {
      files: [...AGENT_DOC_MARKDOWN_PATHS],
      excludeFiles: [],
      options: { ...agentMarkdown },
    },
    { files: ['*.css', '*.scss'], excludeFiles: [], options: { ...css } },
  ] satisfies OxfmtOverrideConfig[],
} satisfies OxfmtConfig);
